# Generated by Django 4.0.4 on 2022-05-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finalproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('name', models.CharField(max_length=50, null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('username', models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='finalproject.authuser')),
            ],
            options={
                'db_table': 'plantmodel',
            },
        ),
    ]
